env:
  es2021: true
  node: true
  browser: true
extends: 
  - airbnb
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
